<?php

namespace Taki47\PrivacyPanel\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Storage;

/**
 * Class PrivacyPanelController
 *
 * @package Modules\PrivacyPanel\Http\Controllers
 *
 * This controller manages user consent for cookies in compliance
 * with GDPR and ePrivacy regulations. It handles both the storing
 * of user preferences and listing the currently stored cookies
 * in the browser categorized by purpose.
 *
 * @author
 *     Lajos Takacs <https://takiwebneked.hu>
 *
 * @version
 *     1.0.0
 *
 * @license
 *     MIT License
 *
 * @example
 *     POST /cookie-consent
 *     {
 *         "necessary": true,
 *         "analytics": false,
 *         "marketing": true
 *     }
 *
 *     GET /cookie-consent/cookies
 *     → Returns categorized cookies currently available
 */
class PrivacyPanelController extends Controller
{
    /**
     * Store the user's cookie consent preferences.
     *
     * The frontend sends a JSON payload describing which cookie
     * categories the user has consented to. This payload is stored
     * as a single JSON-encoded cookie named `cookie_consent`.
     *
     * Lifetime: 1 year
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     *
     * @api
     * @route POST /cookie-consent
     *
     * @example
     *     {
     *         "necessary": true,
     *         "analytics": false,
     *         "marketing": true
     *     }
     */
    public function store(Request $request)
    {
        $consent = $request->all();

        // Queue the consent cookie for 1 year (in minutes)
        $cookie = Cookie::make(
            'cookie-consent',
            json_encode($consent),
            60 * 24 * 365,
            '/',
            null,
            false,          // secure (HTTPS-en true)
            false,          // httpOnly
            false,
            'Lax'
        );

        return response()->json(['status' => 'ok'])->withCookie($cookie);
    }

    /**
     * Returns all known cookies categorized by purpose and grouped by provider.
     *
     * The method reads a local cookie-scan.json file generated by the audit tool,
     * then builds a structured array:
     *
     * {
     *   "necessary": {
     *       "Application": [
     *           { "name": "XSRF-TOKEN", "description": "...", "expiry": "Session", "url": null },
     *           ...
     *       ]
     *   },
     *   "statistics": {
     *       "Google Analytics": [
     *           { "name": "_ga", "description": "...", "expiry": "2 years", "url": "https://..." },
     *           ...
     *       ]
     *   }
     * }
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function list(Request $request)
    {
        if (!Storage::disk('local')->exists('panel-scan.json')) {
            return response()->json(['error' => 'panel-scan.json not found'], 404);
        }

        // Decode JSON and validate structure
        $data = json_decode(Storage::disk('local')->get('panel-scan.json'), true);

        if (!isset($data['cookies']) || !is_array($data['cookies'])) {
            return response()->json(['error' => 'Invalid cookie-scan.json format'], 422);
        }

        $structured = [];

        foreach ($data['cookies'] as $cookie) {
            $category = $cookie['category'] ?? 'others';
            $provider = $cookie['provider'] ?? 'Unknown Provider';

            // Normalize category name to match frontend keys
            $category = strtolower($category);
            if ($category === 'statistics') {
                $category = 'analytics'; // keep consistent with JS translations
            }

            // Initialize nested arrays
            if (!isset($structured[$category])) {
                $structured[$category] = [];
            }
            if (!isset($structured[$category][$provider])) {
                $structured[$category][$provider] = [];
            }

            $structured[$category][$provider][] = [
                'name' => $cookie['name'] ?? '',
                'description' => $cookie['description'] ?? '',
                'expiry' => $cookie['expiry'] ?? 'Session',
                'url' => $cookie['url'] ?? null,
            ];
        }

        return response()->json($structured);
    }

    /**
     * Determine if a cookie is considered "necessary".
     *
     * @param  string  $name
     * @return bool
     */
    protected function isNecessary(string $name): bool
    {
        return str_contains($name, 'XSRF') || str_contains($name, 'session');
    }

    /**
     * Determine if a cookie is an "analytics" cookie.
     *
     * @param  string  $name
     * @return bool
     */
    protected function isAnalytics(string $name): bool
    {
        return str_contains($name, 'ga') || str_contains($name, '_gid');
    }

    /**
     * Determine if a cookie is a "marketing" cookie.
     *
     * @param  string  $name
     * @return bool
     */
    protected function isMarketing(string $name): bool
    {
        return str_contains($name, 'fb') || str_contains($name, 'pixel');
    }

    /**
     * Format a cookie entry for JSON output.
     *
     * @param  string  $name
     * @param  string|null  $value
     * @return array{name: string, value: string}
     */
    protected function formatCookie(string $name, ?string $value): array
    {
        return [
            'name' => $name,
            'value' => $value ?? '',
        ];
    }
}
